[package]
name = "binary-trees-O3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bumpalo = "3.9.1"
rayon = "1.5"
typed-arena = "2.0.1"
toolshed = "0.8.1"